### ISSUE TITLE
Icon button missing in fullpage databases

### ISSUE THREAD

**Issue by fabiosangregorio** [notion-enhancer/icons#6]
"Icons" button is missing in fullpage databases when opening them by clicking on a linked database name.

Steps to reproduce:

1. Have one full-page database in the sidebar root
1. Have one page in the sidebar root
1. Include a linked database linking to the db in step 1
1. Click the name of the db in the top of the linked database 
1. Click on the emoji to try to change it. The button "icons" is missing.

Are you able to reproduce?

(Running on the latest dev build on win10)

**Comment by CloudHill** [comment]
@fabiosangregorio this should now be fixed by the recent pull request.

**Comment by fabiosangregorio** [comment]
Yep, now it works everywhere. Thank you very much!
